lib/sapna_gale_test/backend/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :dashboards, only: [] do
      collection do
        get :home
      end
    end

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
      resources :promotion_codes, only: [:index]
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :variant_property_rule_values, only: [:destroy] do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
      resources :prices, only: [:destroy, :index, :edit, :update, :new, :create]
    end
    get '/products/:product_slug/stock', to: "stock_items#index", as: :product_stock

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        put :advance
        get :confirm
        put :complete
        post :resend
        get "/adjustments/unfinalize", to: "orders#unfinalize_adjustments"
        get "/adjustments/finalize", to: "orders#finalize_adjustments"
        put :approve
        put :cancel
        put :resume
      end

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments, only: [:index, :new, :show, :create] do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end

      resources :cancellations, only: [:index] do
        collection do
          post :short_ship
        end
      end
    end

    resource :general_settings, only: [:edit, :update] do
      collection do
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :adjustment_reasons, except: [:show, :destroy]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories

    resources :stock_transfers, except: [:destroy] do
      member do
        get :receive
        put :finalize
        put :close
        get :tracking_info
        put :ship
      end
    end

    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
        post :update_positions
      end
    end

    resources :stock_items, except: [:show, :new, :edit]
    resources :tax_rates

    resources :trackers
    resources :payment_methods do
      collection do
        post :update_positions
      end
    end

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
      resources :store_credits, except: [:destroy] do
        member do
          get :edit_amount
          put :update_amount
          get :edit_validity
          put :invalidate
        end
      end
    end

    resources :style_guide, only: [:index]
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

lib/sapna_gale_test/backend/app/controllers/spree/admin/store_credits_controller.rb
module Spree
  module Admin
    class StoreCreditsController < ResourceController
      belongs_to 'spree/user', model_class: Spree.user_class
      before_action :load_categories, only: [:new]
      before_action :load_update_reasons, only: [:edit_amount, :edit_validity]
      before_action :ensure_update_reason, only: [:update_amount, :invalidate]

      helper Spree::Admin::StoreCreditEventsHelper

      def show
        @store_credit_events = @store_credit.store_credit_events.chronological
      end

      def create
        @store_credit = @user.store_credits.build(
          permitted_resource_params.merge({
            created_by: try_spree_current_user,
            action_originator: try_spree_current_user
          })
        )

        if @store_credit.save
          flash[:success] = flash_message_for(@store_credit, :successfully_created)
          redirect_to admin_user_store_credits_path(@user)
        else
          load_categories
          flash[:error] = "#{Spree.t('admin.store_credits.unable_to_create')} #{@store_credit.errors.full_messages}"
          render :new
        end
      end

      def update
        @store_credit.assign_attributes(permitted_resource_params)
        @store_credit.created_by = try_spree_current_user

        if @store_credit.save
          respond_to do |format|
            format.json { render json: { message: flash_message_for(@store_credit, :successfully_updated) }, status: :ok }
          end
        else
          respond_to do |format|
            format.json { render json: { message: "#{Spree.t('admin.store_credits.unable_to_update')} #{@store_credit.errors.full_messages}" }, status: :bad_request }
          end
        end
      end

      def update_amount
        @store_credit = @user.store_credits.find(params[:id])
        amount = params.require(:store_credit).require(:amount)
        if @store_credit.update_amount(amount, @update_reason, try_spree_current_user)
          flash[:success] = flash_message_for(@store_credit, :successfully_updated)
          redirect_to admin_user_store_credit_path(@user, @store_credit)
        else
          render_edit_page
        end
      end

      def invalidate
        @store_credit = @user.store_credits.find(params[:id])
        if @store_credit.invalidate(@update_reason, try_spree_current_user)
          redirect_to admin_user_store_credit_path(@user, @store_credit)
        else
          render_edit_page
        end
      end

      private

      def permitted_resource_params
        params.require(:store_credit).permit([:amount, :category_id, :memo]).
          merge(currency: Spree::Config[:currency], created_by: try_spree_current_user)
      end

      def collection
        @collection = super.reverse_order
      end

      def load_update_reasons
        @update_reasons = Spree::StoreCreditUpdateReason.all.order(:name)
      end

      def load_categories
        @credit_categories = Spree::StoreCreditCategory.all.order(:name)
      end

      def ensure_update_reason
        @update_reason = Spree::StoreCreditUpdateReason.find_by(id: params[:update_reason_id])
        unless @update_reason
          @store_credit.errors.add(:base, Spree.t("admin.store_credits.errors.update_reason_required"))
          render_edit_page
        end
      end

      def render_edit_page
        if action == :update_amount
          template = :edit_amount
          translation_key = 'update'
        else
          template = :edit_validity
          translation_key = 'invalidate'
        end

        load_update_reasons
        flash[:error] = "#{Spree.t("admin.store_credits.unable_to_#{translation_key}")}: #{@store_credit.errors.full_messages.join(', ')}"
        render(template) && return
      end
    end
  end
end

lib/sapna_gale_test/backend/app/views/spree/admin/store_credits/_form.html.erb
<div data-hook="admin_store_credit_form_fields" class="row">
  <div class="alpha twelve columns">
    <%= f.field_container :amount do %>
      <%= f.label :amount, class: 'required' %><br />
      <%= f.number_field :amount, min: 0.00, step: :any %>
      <%= f.error_message_on :amount %>
    <% end %>
  </div>
  <div class="alpha twelve columns">
    <%= f.field_container :category do %>
      <%= f.label :category_id, class: 'required' %><br />
      <%= f.select :category_id, options_from_collection_for_select(@credit_categories, :id, :name, f.object.category.try(:id)),
        { include_blank: true }, { class: 'select2 fullwidth', placeholder: Spree.t("admin.store_credits.select_reason") } %>
      <%= f.error_message_on :category %>
    <% end %>
  </div>
  <div data-hook="admin_store_credit_memo_field" class="alpha twelve columns">
    <%= f.field_container :memo do %>
      <%= f.label :memo %>
      <%= f.text_area :memo, class: "fullwidth" %>
      <%= f.error_message_on :memo %>
    <% end %>
  </div>
</div>

lib/sapna_gale_test/backend/app/views/spree/admin/store_credits/_update_reason_field.html.erb
<div class="alpha twelve columns">
  <%= f.field_container :reason do %>
    <%= f.label :reason, Spree.t(:reason), class: 'required' %><br />
    <%= select_tag :update_reason_id, options_from_collection_for_select(@update_reasons, :id, :name),
      { include_blank: true , class: 'select2 fullwidth', placeholder: Spree.t("admin.store_credits.select_amount_update_reason") } %>
    <%= f.error_message_on :reason %>
  <% end %>
</div>

lib/sapna_gale_test/backend/app/views/spree/admin/store_credits/edit_amount.html.erb
<% content_for :page_title do %>
  <%= link_to "#{Spree.t(:editing_user)} #{@user.email}", edit_admin_user_url(@user) %>
<% end %>

<%= render 'spree/admin/users/sidebar' %>
<%= render 'spree/admin/users/tabs', current: :store_credits %>
<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'arrow-left', Spree.t("admin.store_credits.back_to_edit"), admin_user_store_credit_path(@user, @store_credit), class: 'button' %></li>
<% end %>

<%= form_for [:admin, @user, @store_credit], url: update_amount_admin_user_store_credit_path, method: :put do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t("admin.store_credits.edit_amount") %></legend>
    <div data-hook="admin_store_credit_form_fields" class="row">
      <div class="alpha twelve columns">
        <%= f.field_container :amount do %>
          <%= f.label :amount, class: 'required' %><br />
          <%= f.number_field :amount, min: 0.00, step: :any %>
          <%= f.error_message_on :amount %>
        <% end %>
      </div>
      <%= render partial: 'update_reason_field', locals: { f: f } %>
    </div>
    <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: admin_user_store_credits_path(@user, @store_credit) } %>
  </fieldset>
<% end %>

lib/sapna_gale_test/backend/app/views/spree/admin/store_credits/edit_validity.html.erb
<% content_for :page_title do %>
  <%= link_to "#{Spree.t(:editing_user)} #{@user.email}", edit_admin_user_url(@user) %>
<% end %>

<%= render 'spree/admin/users/sidebar' %>
<%= render 'spree/admin/users/tabs', current: :store_credits %>
<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'arrow-left', Spree.t("admin.store_credits.back_to_edit"), admin_user_store_credit_path(@user, @store_credit), class: 'button' %></li>
<% end %>

<%= form_for [:admin, @user, @store_credit], url: invalidate_admin_user_store_credit_path, method: :put do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t("admin.store_credits.invalidate_store_credit") %></legend>
    <div data-hook="admin_store_credit_form_fields" class="row">
      <%= render partial: 'update_reason_field', locals: { f: f } %>
    </div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('store_credit.actions.invalidate'), 'ban' %>
      <%= button_link_to Spree.t('actions.cancel'), admin_user_store_credit_path(@user, @store_credit), icon: 'remove' %>
    </div>
  </fieldset>
<% end %>

lib/sapna_gale_test/backend/app/views/spree/admin/store_credits/index.html.erb
<% content_for :page_title do %>
  <%= link_to "#{Spree.t(:editing_user)} #{@user.email}", edit_admin_user_url(@user) %>
<% end %>

<%= render 'spree/admin/users/sidebar' %>
<%= render 'spree/admin/users/tabs', current: :store_credits %>
<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'arrow-left', Spree.t("admin.store_credits.back_to_user_list"), admin_users_path, class: 'button' %></li>
  <% if can?(:create, Spree::StoreCredit) %>
    <li><%= link_to_with_icon 'plus', Spree.t("admin.store_credits.add"), new_admin_user_store_credit_path(@user), class: 'button' %></li>
  <% end %>
<% end %>

<% if @store_credits.any? %>
  <div id='sc-current-balance'>
    <strong><%= Spree.t("admin.store_credits.current_balance") %> </strong><%= @user.display_total_available_store_credit %>
  </div>

  <table>
    <thead>
      <th><%= Spree::StoreCredit.human_attribute_name(:amount_credited) %></th>
      <th><%= Spree::StoreCredit.human_attribute_name(:amount_used) %></th>
      <th><%= Spree::StoreCredit.human_attribute_name(:amount_authorized) %></th>
      <th><%= Spree::StoreCredit.human_attribute_name(:category_id) %></th>
      <th><%= Spree::StoreCredit.human_attribute_name(:created_by_id) %></th>
      <th><%= Spree::StoreCredit.human_attribute_name(:created_at) %></th>
      <th><%= Spree::StoreCredit.human_attribute_name(:invalidated_at) %></th>
      <th data-hook="admin_store_credits_index_header_actions" class="actions"></th>
    <thead>
    <tbody>
      <% @store_credits.each do |store_credit| %>
        <tr>
          <td class='align-center'>
            <span><%= store_credit.display_amount.to_html %></span>
          </td>
          <td class='align-center'>
            <span><%= store_credit.display_amount_used.to_html %></span>
          </td>
          <td class='align-center'>
            <span><%= store_credit.display_amount_authorized.to_html %></span>
          </td>
          <td class='align-center'>
            <span><%= store_credit.category_name %></span>
          </td>
          <td>
            <span><%= store_credit.created_by_email %></span>
          </td>
          <td class='align-center'>
            <span><%= l store_credit.created_at.to_date %></span>
          </td>
          <td class='align-center'>
            <span><%= store_credit.invalidated? %></span>
          </td>
          <td class="actions" data-hook="admin_store_credits_index_row_actions">
            <% if can?(:show, store_credit) %>
              <%= link_to_edit_url admin_user_store_credit_path(@user, store_credit), { no_text: true, class: 'edit' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::StoreCredit,
                 new_resource_url: new_object_url %>
  </div>
<% end %>

lib/sapna_gale_test/backend/app/views/spree/admin/store_credits/new.html.erb
<% content_for :page_title do %>
  <%= link_to "#{Spree.t(:editing_user)} #{@user.email}", edit_admin_user_url(@user) %>
<% end %>

<%= render 'spree/admin/users/sidebar' %>
<%= render 'spree/admin/users/tabs', current: :store_credits %>
<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'arrow-left', Spree.t("admin.store_credits.back_to_store_credit_list"), admin_user_store_credits_path(@user), class: 'button' %></li>
<% end %>

<%= form_for [:admin, @user, @store_credit] do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t("admin.store_credits.new") %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links', :locals => { :collection_url => admin_user_store_credits_path(@user) } %>
  </fieldset>
<% end %>

lib/sapna_gale_test/backend/app/views/spree/admin/store_credits/show.html.erb
<% content_for :page_title do %>
  <%= link_to "#{Spree.t(:editing_user)} #{@user.email}", edit_admin_user_url(@user) %>
<% end %>

<%= render 'spree/admin/users/sidebar' %>
<%= render 'spree/admin/users/tabs', current: :store_credits %>
<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'arrow-left', Spree.t("admin.store_credits.back_to_store_credit_list"), admin_user_store_credits_path(@user), class: 'button' %></li>
  <% if @store_credit.editable? && can?(:edit, @store_credit) %>
    <li><%= link_to_with_icon 'dollar', Spree.t("admin.store_credits.change_amount"), edit_amount_admin_user_store_credit_path(@user, @store_credit), class: 'button' %></li>
  <% end %>
  <% if @store_credit.invalidateable? && can?(:invalidate, @store_credit) %>
    <li><%= link_to_with_icon 'ban', Spree.t("invalidate"), edit_validity_admin_user_store_credit_path(@user, @store_credit), class: 'button' %></li>
  <% end %>
<% end %>

<table id='sc-detail-table'>
  <colgroup>
    <col style="width: 20%;" />
    <col style="width: 65%;" />
    <col style="width: 15%;" />
  </colgroup>
  <tr>
    <td>
      <strong><%= Spree::StoreCredit.human_attribute_name(:amount) %>:</strong>
    </td>
    <td><%= @store_credit.display_amount.to_html %></td>
    <td class='actions'></td>
  </tr>
  <tr>
    <td>
      <strong><%= Spree::StoreCredit.human_attribute_name(:created_by_id) %>:</strong>
    </td>
    <td><%= @store_credit.created_by_email %></td>
    <td class='actions'></td>
  </tr>
  <tr>
    <td>
      <strong><%= Spree.t("admin.store_credits.credit_type") %>:</strong>
    </td>
    <td><%= @store_credit.category_name %></td>
    <td class='actions'></td>
  </tr>
  <tr id='memo-display-row'>
    <td>
      <strong><%= Spree::StoreCredit.human_attribute_name(:memo) %>:</strong>
    </td>
    <td class='js-memo-text'>
      <%= @store_credit.memo %>
    </td>
    <td class='actions align-center'>
      <% if can?(:update, @store_credit) %>
        <%= link_to '', '#', class: 'js-edit-memo edit-method fa fa-edit no-text with-tip', data: { action: 'edit' }, title: Spree.t('actions.edit') %>
      <% end %>
    </td>
  </tr>
  <tr id='memo-edit-row' class='hidden' data-original-value='<%= @store_credit.memo %>'>
    <td>
      <strong><%= Spree::StoreCredit.human_attribute_name(:memo) %>:</strong>
    </td>
    <td>
      <%= form_tag admin_user_store_credit_path(@user, @store_credit), method: :put, remote: true, id: 'sc_memo_edit_form' do %>
        <%= text_area_tag 'store_credit[memo]', @store_credit.memo  %>
      <% end %>
    </td>
    <td class='actions align-center'>
      <% if can?(:update, @store_credit) %>
        <%= link_to '', '#', class: 'js-save-memo fa fa-check no-text with-tip', data: { user_id: @user.id, store_credit_id: @store_credit.id, action: 'save' }, title: Spree.t('actions.save') %>
        <%= link_to '', '#', class: 'js-cancel-memo fa fa-void no-text with-tip', data: { action: 'void' }, title: Spree.t('actions.cancel') %>
      <% end %>
    </td>
  </tr>
</table>

<fieldset>
  <legend align='center'><%= Spree.t("admin.store_credits.history") %></legend>
  <table>
    <colgroup>
      <col style="width: 15%;" />
      <col style="width: 10%;" />
      <col style="width: 10%;" />
      <col style="width: 25%;" />
      <col style="width: 10%;" />
      <col style="width: 30%;" />
    </colgroup>
    <thead>
      <tr>
        <th><%= Spree.t(:date) %></th>
        <th><%= Spree::StoreCreditEvent.human_attribute_name(:action) %></th>
        <th><%= Spree::StoreCredit.human_attribute_name(:amount) %></th>
        <th><%= Spree::StoreCredit.human_attribute_name(:created_by_id) %></th>
        <th><%= Spree::StoreCreditEvent.human_attribute_name(:user_total_amount) %></th>
        <th><%= Spree::StoreCreditUpdateReason.human_attribute_name(:name) %></th>
      </tr>
    </thead>
    <tbody>
      <% @store_credit_events.each do |event| %>
        <tr>
          <td data-hook="admin_show_store_credit_date_cell">
            <%= pretty_time(event.created_at) %>
          </td>
          <td><%= store_credit_event_admin_action_name(event) %></td>
          <td class='align-right'><%= event.display_amount %></td>
          <td><%= store_credit_event_originator_link(event) %></td>
          <td class='align-right'><%= event.display_user_total_amount %></td>
          <td><%= event.update_reason.try!(:name) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</fieldset>