lib/sapna_gale_test/backend/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :dashboards, only: [] do
      collection do
        get :home
      end
    end

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
      resources :promotion_codes, only: [:index]
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :variant_property_rule_values, only: [:destroy] do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
      resources :prices, only: [:destroy, :index, :edit, :update, :new, :create]
    end
    get '/products/:product_slug/stock', to: "stock_items#index", as: :product_stock

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        put :advance
        get :confirm
        put :complete
        post :resend
        get "/adjustments/unfinalize", to: "orders#unfinalize_adjustments"
        get "/adjustments/finalize", to: "orders#finalize_adjustments"
        put :approve
        put :cancel
        put :resume
      end

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments, only: [:index, :new, :show, :create] do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end

      resources :cancellations, only: [:index] do
        collection do
          post :short_ship
        end
      end
    end

    resource :general_settings, only: [:edit, :update] do
      collection do
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :adjustment_reasons, except: [:show, :destroy]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories

    resources :stock_transfers, except: [:destroy] do
      member do
        get :receive
        put :finalize
        put :close
        get :tracking_info
        put :ship
      end
    end

    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
        post :update_positions
      end
    end

    resources :stock_items, except: [:show, :new, :edit]
    resources :tax_rates

    resources :trackers
    resources :payment_methods do
      collection do
        post :update_positions
      end
    end

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
      resources :store_credits, except: [:destroy] do
        member do
          get :edit_amount
          put :update_amount
          get :edit_validity
          put :invalidate
        end
      end
    end

    resources :style_guide, only: [:index]
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

lib/sapna_gale_test/backend/app/controllers/spree/admin/stock_movements_controller.rb
module Spree
  module Admin
    class StockMovementsController < ResourceController
      belongs_to 'spree/stock_location'
      before_action :parent

      private

      def permitted_resource_params
        params.require(:stock_movement).permit(:quantity, :stock_item_id, :action)
      end

      def collection
        super.
          recent.
          includes(stock_item: { variant: :product }).
          page(params[:page])
      end
    end
  end
end

lib/sapna_gale_test/backend/app/helpers/spree/admin/stock_movements_helper.rb
module Spree
  module Admin
    module StockMovementsHelper
      def pretty_originator(stock_movement)
        if stock_movement.originator.respond_to?(:number)
          if stock_movement.originator.respond_to?(:order)
            link_to stock_movement.originator.number, [:edit, :admin, stock_movement.originator.order]
          else
            stock_movement.originator.number
          end
        else
          ""
        end
      end

      def display_variant(stock_movement)
        variant = stock_movement.stock_item.variant
        output = [variant.name]
        output << variant.options_text unless variant.options_text.blank?
        safe_join(output, "<br />".html_safe)
      end
    end
  end
end

lib/sapna_gale_test/backend/app/views/spree/admin/stock_movements/_form.html.erb
<div data-hook="admin_stock_movements_form_fields" class="row">
  <div class="alpha twelve columns">
    <%= f.field_container :quantity do %>
      <%= f.label :quantity %>
      <%= f.text_field :quantity %>
    <% end %>
    <%= f.field_container :stock_item_id do %>
      <%= f.label :stock_item_id, Spree::StockItem.model_name.human %>
      <%= f.text_field 'stock_item_id', :class => 'fullwidth', :'data-stock-location-id' => params[:stock_location_id] %>
    <% end %>
  </div>
</div>

lib/sapna_gale_test/backend/app/views/spree/admin/stock_movements/index.html.erb
<%= render 'spree/admin/shared/shipping_tabs' %>

<% content_for :page_title do %>
  <%= Spree.t(:stock_movements_for_stock_location, stock_location_name: @stock_location.name) %>
<% end %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::StockMovement) %>
    <li>
      <%= button_link_to Spree.t(:new_stock_movement), new_admin_stock_location_stock_movement_path(@stock_location),  icon: 'plus', id: 'admin_new_stock_movement_link' %>
    </li>
  <% end %>

  <% if can?(:display, Spree::StockLocation) %>
    <li>
      <%= link_to_with_icon 'arrow-left', Spree.t(:back_to_stock_locations_list), admin_stock_locations_path, :class => 'button' %>
    </li>
  <% end %>
<% end %>

<% if @stock_movements.any? %>
<table class="index" id='listing_stock_movements'>
  <colgroup>
    <col style="width: 35%">
    <col style="width: 20%">
    <col style="width: 45%">
  </colgroup>
  <thead>
    <tr data-hook="admin_stock_movements_index_headers">
      <th><%= Spree::StockMovement.human_attribute_name(:stock_item) %>
      <th><%= Spree::StockMovement.human_attribute_name(:quantity) %></th>
      <th><%= Spree::StockMovement.human_attribute_name(:action) %></th>
    </tr>
  </thead>
  <tbody>
    <% @stock_movements.each do |stock_movement|%>
      <tr id="<%= spree_dom_id stock_movement %>" data-hook="admin_stock_movements_index_rows" class="<%= cycle('odd', 'even')%>">
        <td class="align-center">
          <%= display_variant(stock_movement) %>
        </td>
        <td class="align-center"><%= stock_movement.quantity %></td>
        <td class="align-center"><%= pretty_originator(stock_movement) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::StockMovement,
                 new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @stock_movements, theme: "sapna_gale_test_admin" %>

lib/sapna_gale_test/backend/app/views/spree/admin/stock_movements/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_stock_movement) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'arrow-left', Spree.t(:back_to_stock_movements_list), admin_stock_location_stock_movements_path(@stock_location), :class => 'button' %></li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @stock_movement } %>

<%= form_for [:admin, @stock_location, @stock_movement] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links', locals: { collection_url: admin_stock_location_stock_movements_path(@stock_location) } %>
  </fieldset>
<% end %>