lib/sapna_gale_test/frontend/config/routes.rb
Spree::Core::Engine.routes.draw do
  root to: 'home#index'

  resources :products, only: [:index, :show]

  get '/locale/set', to: 'locale#set'

  # non-restful checkout stuff
  patch '/checkout/update/:state', to: 'checkout#update', as: :update_checkout
  get '/checkout/:state', to: 'checkout#edit', as: :checkout_state
  get '/checkout', to: 'checkout#edit', as: :checkout

  populate_redirect = redirect do |_params, request|
    request.flash[:error] = Spree.t(:populate_get_error)
    request.referer || '/cart'
  end

  get '/orders/populate', to: populate_redirect
  get '/orders/:id/token/:token' => 'orders#show', :as => :token_order

  resources :orders, except: [:index, :new, :create, :destroy] do
    post :populate, on: :collection
  end

  get '/cart', to: 'orders#edit', as: :cart
  patch '/cart', to: 'orders#update', as: :update_cart
  put '/cart/empty', to: 'orders#empty', as: :empty_cart

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/content/cvv', to: 'content#cvv', as: :cvv
  get '/cart_link', to: 'store#cart_link', as: :cart_link
end

lib/sapna_gale_test/frontend/app/models/spree/frontend_configuration.rb
module Spree
  class FrontendConfiguration < Preferences::Configuration
    preference :locale, :string, default: Rails.application.config.i18n.default_locale
  end
end

lib/sapna_gale_test/frontend/app/controllers/spree/checkout_controller.rb
module Spree
  # This is somewhat contrary to standard REST convention since there is not
  # actually a Checkout object. There's enough distinct logic specific to
  # checkout which has nothing to do with updating an order that this approach
  # is warranted.
  class CheckoutController < Spree::StoreController
    before_filter :load_order
    around_filter :lock_order
    before_filter :set_state_if_present

    before_action :ensure_order_not_completed
    before_action :ensure_checkout_allowed
    before_action :ensure_sufficient_stock_lines
    before_action :ensure_valid_state

    before_action :associate_user
    before_action :check_authorization
    before_action :apply_coupon_code

    before_action :setup_for_current_state

    helper 'spree/orders'

    rescue_from Spree::Core::GatewayError, with: :rescue_from_spree_gateway_error

    # Updates the order and advances to the next state (when possible.)
    def update
      if OrderUpdateAttributes.new(@order, update_params, request_env: request.headers.env).apply
        @order.temporary_address = !params[:save_user_address]
        success = if @order.state == 'confirm'
          @order.complete
        else
          @order.next
        end
        if !success
          flash[:error] = @order.errors.full_messages.join("\n")
          redirect_to(checkout_state_path(@order.state)) && return
        end

        if @order.completed?
          @current_order = nil
          flash.notice = Spree.t(:order_processed_successfully)
          flash['order_completed'] = true
          redirect_to completion_route
        else
          redirect_to checkout_state_path(@order.state)
        end
      else
        render :edit
      end
    end

    private

    def update_params
      if update_params = massaged_params[:order]
        update_params.permit(permitted_checkout_attributes)
      else
        # We current allow update requests without any parameters in them.
        {}
      end
    end

    def massaged_params
      massaged_params = params.deep_dup

      move_payment_source_into_payments_attributes(massaged_params)
      move_existing_card_into_payments_attributes(massaged_params)
      set_payment_parameters_amount(massaged_params, @order)

      massaged_params
    end

    def ensure_valid_state
      unless skip_state_validation?
        if (params[:state] && !@order.has_checkout_step?(params[:state])) ||
           (!params[:state] && !@order.has_checkout_step?(@order.state))
          @order.state = 'cart'
          redirect_to checkout_state_path(@order.checkout_steps.first)
        end
      end

      # Fix for https://github.com/spree/spree/issues/4117
      # If confirmation of payment fails, redirect back to payment screen
      if params[:state] == "confirm" && @order.payment_required? && @order.payments.valid.empty?
        flash.keep
        redirect_to checkout_state_path("payment")
      end
    end

    # Should be overriden if you have areas of your checkout that don't match
    # up to a step within checkout_steps, such as a registration step
    def skip_state_validation?
      false
    end

    def load_order
      @order = current_order
      redirect_to(spree.cart_path) && return unless @order
    end

    def set_state_if_present
      if params[:state]
        redirect_to checkout_state_path(@order.state) if @order.can_go_to_state?(params[:state]) && !skip_state_validation?
        @order.state = params[:state]
      end
    end

    def ensure_checkout_allowed
      unless @order.checkout_allowed?
        redirect_to spree.cart_path
      end
    end

    def ensure_order_not_completed
      redirect_to spree.cart_path if @order.completed?
    end

    def ensure_sufficient_stock_lines
      if @order.insufficient_stock_lines.present?
        flash[:error] = Spree.t(:inventory_error_flash_for_insufficient_quantity)
        redirect_to spree.cart_path
      end
    end

    # Provides a route to redirect after order completion
    def completion_route
      spree.order_path(@order)
    end

    def setup_for_current_state
      method_name = :"before_#{@order.state}"
      send(method_name) if respond_to?(method_name, true)
    end

    def before_address
      # if the user has a default address, a callback takes care of setting
      # that; but if he doesn't, we need to build an empty one here
      default = { country_id: Country.default.id }
      @order.build_bill_address(default) unless @order.bill_address
      @order.build_ship_address(default) if @order.checkout_steps.include?('delivery') && !@order.ship_address
    end

    def before_delivery
      return if params[:order].present?

      packages = @order.shipments.map(&:to_package)
      @differentiator = Spree::Stock::Differentiator.new(@order, packages)
    end

    def before_payment
      if @order.checkout_steps.include? "delivery"
        packages = @order.shipments.map(&:to_package)
        @differentiator = Spree::Stock::Differentiator.new(@order, packages)
        @differentiator.missing.each do |variant, quantity|
          @order.contents.remove(variant, quantity)
        end
      end

      if try_spree_current_user && try_spree_current_user.respond_to?(:payment_sources)
        @payment_sources = try_spree_current_user.payment_sources
      end
    end

    def rescue_from_spree_gateway_error(exception)
      flash.now[:error] = Spree.t(:spree_gateway_error_flash_for_checkout)
      @order.errors.add(:base, exception.message)
      render :edit
    end

    def check_authorization
      authorize!(:edit, current_order, cookies.signed[:guest_token])
    end
  end
end

lib/sapna_gale_test/frontend/app/controllers/spree/content_controller.rb
module Spree
  class ContentController < Spree::StoreController
    respond_to :html

    def cvv
      render layout: false
    end
  end
end

lib/sapna_gale_test/frontend/app/controllers/spree/home_controller.rb
module Spree
  class HomeController < Spree::StoreController
    helper 'spree/products'
    respond_to :html

    def index
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end
  end
end

lib/sapna_gale_test/frontend/app/controllers/spree/locale_controller.rb
module Spree
  class LocaleController < Spree::StoreController
    def set
      if request.referer && request.referer.starts_with?('http://' + request.host)
        session['user_return_to'] = request.referer
      end
      if params[:locale] && I18n.available_locales.map(&:to_s).include?(params[:locale])
        session[:locale] = I18n.locale = params[:locale]
        flash.notice = Spree.t(:locale_changed)
      else
        flash[:error] = Spree.t(:locale_not_changed)
      end
      redirect_back_or_default(spree.root_path)
    end
  end
end

lib/sapna_gale_test/frontend/app/controllers/spree/orders_controller.rb
module Spree
  class OrdersController < Spree::StoreController
    before_action :check_authorization
    rescue_from ActiveRecord::RecordNotFound, with: :render_404
    helper 'spree/products', 'spree/orders'

    respond_to :html

    before_filter :assign_order, only: :update
    # note: do not lock the #edit action because that's where we redirect when we fail to acquire a lock
    around_filter :lock_order, only: :update
    before_filter :apply_coupon_code, only: :update
    skip_before_filter :verify_authenticity_token, only: [:populate]

    def show
      @order = Order.find_by_number!(params[:id])
    end

    def update
      if @order.contents.update_cart(order_params)
        respond_with(@order) do |format|
          format.html do
            if params.key?(:checkout)
              @order.next if @order.cart?
              redirect_to checkout_state_path(@order.checkout_steps.first)
            else
              redirect_to cart_path
            end
          end
        end
      else
        respond_with(@order)
      end
    end

    # Shows the current incomplete order from the session
    def edit
      @order = current_order || Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
      associate_user
    end

    # Adds a new item to the order (creating a new order if none already exists)
    def populate
      order    = current_order(create_order_if_necessary: true)
      variant  = Spree::Variant.find(params[:variant_id])
      quantity = params[:quantity].to_i

      # 2,147,483,647 is crazy. See issue https://github.com/spree/spree/issues/2695.
      if quantity.between?(1, 2_147_483_647)
        begin
          order.contents.add(variant, quantity)
        rescue ActiveRecord::RecordInvalid => e
          error = e.record.errors.full_messages.join(", ")
        end
      else
        error = Spree.t(:please_enter_reasonable_quantity)
      end

      if error
        flash[:error] = error
        redirect_back_or_default(spree.root_path)
      else
        respond_with(order) do |format|
          format.html { redirect_to cart_path }
        end
      end
    end

    def empty
      if @order = current_order
        @order.empty!
      end

      redirect_to spree.cart_path
    end

    def accurate_title
      if @order && @order.completed?
        Spree.t(:order_number, number: @order.number)
      else
        Spree.t(:shopping_cart)
      end
    end

    def check_authorization
      cookies.permanent.signed[:guest_token] = params[:token] if params[:token]
      order = Spree::Order.find_by_number(params[:id]) || current_order

      if order
        authorize! :edit, order, cookies.signed[:guest_token]
      else
        authorize! :create, Spree::Order
      end
    end

    private

    def order_params
      if params[:order]
        params[:order].permit(*permitted_order_attributes)
      else
        {}
      end
    end

    def assign_order
      @order = current_order
      unless @order
        flash[:error] = Spree.t(:order_not_found)
        redirect_to(root_path) && return
      end
    end
  end
end

lib/sapna_gale_test/frontend/app/controllers/spree/products_controller.rb
module Spree
  class ProductsController < Spree::StoreController
    before_action :load_product, only: :show
    before_action :load_taxon, only: :index

    rescue_from ActiveRecord::RecordNotFound, with: :render_404
    helper 'spree/taxons'

    respond_to :html

    def index
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end

    def show
      @variants = @product.
        variants_including_master.
        display_includes.
        with_prices(current_pricing_options).
        includes([:option_values, :images])

      @product_properties = @product.product_properties.includes(:property)
      @taxon = Spree::Taxon.find(params[:taxon_id]) if params[:taxon_id]
    end

    private

    def accurate_title
      if @product
        @product.meta_title.blank? ? @product.name : @product.meta_title
      else
        super
      end
    end

    def load_product
      if try_spree_current_user.try(:has_spree_role?, "admin")
        @products = Product.with_deleted
      else
        @products = Product.available
      end
      @product = @products.friendly.find(params[:id])
    end

    def load_taxon
      @taxon = Spree::Taxon.find(params[:taxon]) if params[:taxon].present?
    end
  end
end

lib/sapna_gale_test/frontend/app/controllers/spree/store_controller.rb
module Spree
  class StoreController < Spree::BaseController
    include Spree::Core::ControllerHelpers::Pricing
    include Spree::Core::ControllerHelpers::Order

    skip_before_action :set_current_order, only: :cart_link

    def unauthorized
      render 'spree/shared/unauthorized', layout: Spree::Config[:layout], status: 401
    end

    def cart_link
      render partial: 'spree/shared/link_to_cart'
      fresh_when(simple_current_order)
    end

    private

    # This method is placed here so that the CheckoutController
    # and OrdersController can both reference it (or any other controller
    # which needs it)
    def apply_coupon_code
      if params[:order] && params[:order][:coupon_code]
        @order.coupon_code = params[:order][:coupon_code]

        handler = PromotionHandler::Coupon.new(@order).apply

        if handler.error.present?
          flash.now[:error] = handler.error
          respond_with(@order) { |format| format.html { render :edit } } && return
        elsif handler.success
          flash[:success] = handler.success
        end
      end
    end

    def config_locale
      Spree::Frontend::Config[:locale]
    end

    def lock_order
      OrderMutex.with_lock!(@order) { yield }
    rescue Spree::OrderMutex::LockFailed
      flash[:error] = Spree.t(:order_mutex_error)
      redirect_to spree.cart_path
    end
  end
end

lib/sapna_gale_test/frontend/app/controllers/spree/taxons_controller.rb
module Spree
  class TaxonsController < Spree::StoreController
    rescue_from ActiveRecord::RecordNotFound, with: :render_404
    helper 'spree/products'

    respond_to :html

    def show
      @taxon = Taxon.find_by_permalink!(params[:id])
      return unless @taxon

      @searcher = build_searcher(params.merge(taxon: @taxon.id, include_images: true))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end

    private

    def accurate_title
      if @taxon
        @taxon.seo_title
      else
        super
      end
    end
  end
end

lib/sapna_gale_test/frontend/app/views/spree/orders/_adjustment_row.html.erb
<% if adjustments.sum(&:amount) != 0 %>
  <tr class="adjustment">
    <td colspan="4" align='right'><h5><%= type %>: <%= label %></h5></td>
    <td colspan='2'>
      <h5><%= Spree::Money.new(adjustments.sum(&:amount), :currency => @order.currency) %></h5>
    </td>
  </tr>
<% end %>

lib/sapna_gale_test/frontend/app/views/spree/orders/_adjustments.html.erb
<tbody id="cart_adjustments" data-hook>
  <% if @order.line_item_adjustments.exists? %>
    <% @order.line_item_adjustments.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
      <%= render "spree/orders/adjustment_row", :label => label, :adjustments => adjustments, :type => Spree.t(:promotion) %>
    <% end %>
  <% end %>

  <% @order.all_adjustments.tax.eligible.group_by(&:label).each do |label, adjustments| %>
    <%= render "spree/orders/adjustment_row", :label => label, :adjustments => adjustments, :type => Spree.t(:tax) %>
  <% end %>

  <% @order.shipments.each do |shipment| %>
    <tr>
      <td colspan="4" align='right'><h5><%= Spree.t(:shipping) %>: <%= shipment.shipping_method.name %></h5></td>
      <td colspan='2'>
        <h5><%= shipment.display_discounted_cost %></h5>
      </td>
    </tr>
  <% end %>

  <% @order.adjustments.eligible.group_by(&:label).each do |label, adjustments| %>
    <%= render "spree/orders/adjustment_row", :label => label, :adjustments => adjustments, :type => Spree.t(:adjustment) %>
  <% end %>
</tbody>

lib/sapna_gale_test/frontend/app/views/spree/orders/_form.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
<table id="cart-detail" data-hook>
  <thead>
    <tr data-hook="cart_items_headers">
      <th class="cart-item-description-header" colspan="2"><%= Spree.t(:item) %></th>
      <th class="cart-item-price-header"><%= Spree.t(:price) %></th>
      <th class="cart-item-quantity-header"><%= Spree.t(:qty) %></th>
      <th class="cart-item-total-header"><%= Spree.t(:total) %></th>
      <th class="cart-item-delete-header"></th>
    </tr>
  </thead>
  <tbody id="line_items" data-hook>
    <%= render partial: 'spree/orders/line_item', collection: order_form.object.line_items, locals: {order_form: order_form} %>
  </tbody>
  <% if @order.adjustments.nonzero.exists? || @order.line_item_adjustments.nonzero.exists? || @order.shipment_adjustments.nonzero.exists? || @order.shipments.any? %>
    <tr class="cart-subtotal">
      <td colspan="4" align='right'><h5><%= Spree.t(:cart_subtotal, :count => @order.line_items.sum(:quantity)) %></h5></th>
      <td colspan><h5><%= order_form.object.display_item_total %></h5></td>
      <td></td>
    </tr>
    <%= render "spree/orders/adjustments" %>
  <% end %>
  <tr class="cart-total">
    <td colspan="4" align='right'><h5><%= Spree.t(:total) %></h5></th>
    <td colspan><h5><%= order_form.object.display_total %></h5></td>
    <td></td>
  </tr>
</table>

lib/sapna_gale_test/frontend/app/views/spree/orders/_line_item.html.erb
<% variant = line_item.variant -%>
<%= order_form.fields_for :line_items, line_item do |item_form| -%>
  <tr class="<%= cycle('', 'alt') %> line-item">
    <td class="cart-item-image" data-hook="cart_item_image">
      <% if variant.images.length == 0 %>
        <%= link_to image_tag(variant.product.display_image.attachment(:small)), variant.product %>
      <% else %>
        <%= link_to image_tag(variant.images.first.attachment.url(:small)), variant.product %>
      <% end %>
    </td>
    <td class="cart-item-description" data-hook="cart_item_description">
      <h4><%= link_to line_item.name, product_path(variant.product) %></h4>
      <%= variant.options_text %>
      <% if line_item.insufficient_stock? %>
        <span class="out-of-stock">
          <%= Spree.t(:out_of_stock) %>&nbsp;&nbsp;<br />
        </span>
      <% end %>
      <span class="line-item-description" data-hook="line_item_description">
        <%= line_item_description_text(line_item.description) %>
      </span>
    </td>
    <td class="cart-item-price" data-hook="cart_item_price">
      <%= line_item.single_money.to_html %>
    </td>
    <td class="cart-item-quantity" data-hook="cart_item_quantity">
      <%= item_form.number_field :quantity, :min => 0, :class => "line_item_quantity", :size => 5 %>
    </td>
    <td class="cart-item-total" data-hook="cart_item_total">
      <%= line_item.display_amount.to_html unless line_item.quantity.nil? %>
    </td>
    <td class="cart-item-delete" data-hook="cart_item_delete">
      <%= link_to image_tag('icons/delete.png'), '#', :class => 'delete', :id => "delete_#{dom_id(line_item)}" %>
    </td>
  </tr>
<% end -%>

lib/sapna_gale_test/frontend/app/views/spree/orders/edit.html.erb
<% @body_id = 'cart' %>
<div data-hook="cart_container">
  <h1><%= Spree.t(:shopping_cart) %></h1>

  <% if @order.line_items.empty? %>

    <div data-hook="empty_cart">
      <p><%= Spree.t(:your_cart_is_empty) %></p>
      <p><%= link_to Spree.t(:continue_shopping), products_path, :class => 'button continue' %></p>
    </div>

  <% else %>

    <div data-hook="outside_cart_form">
      <%= form_for @order, :url => update_cart_path, :html => {:id => 'update-cart'} do |order_form| %>
        <div data-hook="inside_cart_form">

          <div data-hook="cart_items">
            <%= render :partial => 'form', :locals => { :order_form => order_form } %>
          </div>

          <div class="links columns sixteen alpha omega" data-hook="cart_buttons">
            <%= order_form.text_field :coupon_code, :size => 10, :placeholder => Spree.t(:coupon_code) %>
            <%= button_tag :class => 'primary', :id => 'update-button' do %>
              <%= Spree.t(:update) %>
            <% end %>
            <%= button_tag :class => 'button checkout primary', :id => 'checkout-link', :name => 'checkout' do %>
              <%= Spree.t(:checkout) %>
            <% end %>
          </div>

        </div>
      <% end %>
    </div>

    <div id="empty-cart" data-hook>
      <%= form_tag empty_cart_path, :method => :put do %>
        <p id="clear_cart_link" data-hook>
        <%= submit_tag Spree.t(:empty_cart), :class => 'button gray' %>
        <%= Spree.t(:or) %>
        <%= link_to Spree.t(:continue_shopping), products_path, :class => 'continue button gray' %>
        </p>
      <% end %>
    </div>

  <% end %>
</div>

lib/sapna_gale_test/frontend/app/views/spree/orders/show.html.erb
<fieldset id="order_summary" data-hook>
  <legend><%= Spree.t(:order_number, :number => @order.number) %></legend>
  <h1><%= accurate_title %></h1>
  <% if order_just_completed?(@order) %>
    <strong><%= Spree.t(:thank_you_for_your_order) %></strong>
  <% end %>

  <div id="order" data-hook>
    <%= render :partial => 'spree/shared/order_details', :locals => { :order => @order } %>

    <br class="clear" />

    <p data-hook="links">
      <%= link_to Spree.t(:back_to_store), spree.root_path, :class => "button" %>
      <% unless order_just_completed?(@order) %>
        <% if try_spree_current_user && respond_to?(:account_path) %>
          <%= link_to Spree.t(:my_account), spree.account_path, :class => "button" %>
        <% end %>
      <% end %>
    </p>
  </div>
</fieldset>