lib/sapna_gale_test/backend/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :dashboards, only: [] do
      collection do
        get :home
      end
    end

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
      resources :promotion_codes, only: [:index]
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :variant_property_rule_values, only: [:destroy] do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
      resources :prices, only: [:destroy, :index, :edit, :update, :new, :create]
    end
    get '/products/:product_slug/stock', to: "stock_items#index", as: :product_stock

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        put :advance
        get :confirm
        put :complete
        post :resend
        get "/adjustments/unfinalize", to: "orders#unfinalize_adjustments"
        get "/adjustments/finalize", to: "orders#finalize_adjustments"
        put :approve
        put :cancel
        put :resume
      end

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments, only: [:index, :new, :show, :create] do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end

      resources :cancellations, only: [:index] do
        collection do
          post :short_ship
        end
      end
    end

    resource :general_settings, only: [:edit, :update] do
      collection do
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :adjustment_reasons, except: [:show, :destroy]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories

    resources :stock_transfers, except: [:destroy] do
      member do
        get :receive
        put :finalize
        put :close
        get :tracking_info
        put :ship
      end
    end

    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
        post :update_positions
      end
    end

    resources :stock_items, except: [:show, :new, :edit]
    resources :tax_rates

    resources :trackers
    resources :payment_methods do
      collection do
        post :update_positions
      end
    end

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
      resources :store_credits, except: [:destroy] do
        member do
          get :edit_amount
          put :update_amount
          get :edit_validity
          put :invalidate
        end
      end
    end

    resources :style_guide, only: [:index]
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

lib/sapna_gale_test/backend/app/controllers/spree/admin/promotions_controller.rb
module Spree
  module Admin
    class PromotionsController < ResourceController
      before_action :load_data
      before_action :load_bulk_code_information, only: [:edit]

      create.before :build_promotion_codes

      helper 'spree/promotion_rules'

      def create
        @promotion_builder = Spree::PromotionBuilder.new(
          permitted_promo_builder_params.merge(user: try_spree_current_user),
          permitted_resource_params
        )
        @promotion = @promotion_builder.promotion

        if @promotion_builder.perform
          flash[:success] = Spree.t(:promotion_successfully_created)
          redirect_to location_after_save
        else
          flash[:error] = @promotion_builder.errors.full_messages.join(", ")
          render action: 'new'
        end
      end

      private

      def load_bulk_code_information
        @promotion_builder = Spree::PromotionBuilder.new(
          base_code: @promotion.codes.first.try!(:value),
          number_of_codes: @promotion.codes.count
        )
      end

      def location_after_save
        spree.edit_admin_promotion_url(@promotion)
      end

      def load_data
        @calculators = Rails.application.config.spree.calculators.promotion_actions_create_adjustments
        @promotion_categories = Spree::PromotionCategory.order(:name)
      end

      def collection
        return @collection if defined?(@collection)
        params[:q] ||= HashWithIndifferentAccess.new
        params[:q][:s] ||= 'id desc'

        @collection = super
        @search = @collection.ransack(params[:q])
        @collection = @search.result(distinct: true).
          includes(promotion_includes).
          page(params[:page]).
          per(params[:per_page] || Spree::Config[:promotions_per_page])

        @collection
      end

      def promotion_includes
        [:promotion_actions]
      end

      def permitted_promo_builder_params
        if params[:promotion_builder]
          params[:promotion_builder].permit(:base_code, :number_of_codes)
        else
          {}
        end
      end
    end
  end
end

lib/sapna_gale_test/backend/app/views/spree/admin/promotions/_actions.html.erb
<fieldset id="action_fields" class="eight columns omega no-border-top">

  <%= form_tag spree.admin_promotion_promotion_actions_path(@promotion), :remote => true, :id => 'new_promotion_action_form' do %>
    <% options = options_for_select(  Rails.application.config.spree.promotions.actions.map(&:name).map {|name| [ Spree.t("promotion_action_types.#{name.demodulize.underscore}.name"), name] } ) %>
    <fieldset>
      <legend align="center"><%= Spree::PromotionAction.model_name.human(count: :other) %></legend>
      <% if can?(:update, @promotion) %>
        <div class="field">
          <%= label_tag :action_type, Spree.t(:add_action_of_type)%>
          <%= select_tag 'action_type', options, :class => 'select2 fullwidth' %>
        </div>
        <div class="filter-actions actions">
          <%= button Spree.t('actions.add'), 'plus' %>
        </div>
      <% end %>
    </fieldset>
  <% end %>

  <%= form_for @promotion, :url => spree.admin_promotion_path(@promotion), :method => :put do |f| %>
    <div id="actions" class="filter_list">
      <% if @promotion.actions.any? %>
        <%= render :partial => 'promotion_action',  :collection => @promotion.actions %>
      <% else %>
        <div class="no-objects-found">
          <%= Spree.t(:no_actions_added) %>
        </div>
      <% end %>
    </div>
    <% if can?(:update, @promotion) %>
      <div class="filter-actions actions promotion-update">
        <%= button Spree.t('actions.update'), 'refresh' %>
      </div>
    <% end %>
  <% end %>

</fieldset>

lib/sapna_gale_test/backend/app/views/spree/admin/promotions/_form.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @promotion } %>
<div class="row">
  <div id="general_fields" class="alpha thirteen columns">
    <div class="alpha four columns">
      <%= f.field_container :name do %>
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'fullwidth' %>
      <% end %>

      <%= fields_for :promotion_builder do |bf| %>
        <%= bf.field_container :base_code do %>
          <%= bf.label :base_code %>
          <%= bf.text_field :base_code, :readonly => !@promotion.new_record?, :class => 'fullwidth' %>
        <% end %>

        <%= bf.field_container :number_of_codes do %>
          <%= bf.label :number_of_codes %>
          <%= bf.text_field :number_of_codes, :readonly => !@promotion.new_record?, class: 'fullwidth' %>
        <% end %>
      <% end %>

      <%= f.field_container :per_code_usage_limit do %>
        <%= f.label :per_code_usage_limit %>
        <%= f.text_field :per_code_usage_limit, class: 'fullwidth' %>
      <% end %>

      <%= f.field_container :path do %>
        <%= f.label :path %>
        <%= f.text_field :path, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :advertise do %>
        <%= f.check_box :advertise %>
        <%= f.label :advertise %>
      <% end %>

      <%= f.field_container :apply_automatically do %>
        <%= f.check_box :apply_automatically %>
        <%= f.label :apply_automatically %>
      <% end %>
    </div>

    <div class="omega nine columns">
      <%= f.field_container :description do %>
        <%= f.label :description %><br />
        <%= f.text_area :description, :rows => 7, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :category do %>
        <%= f.label :promotion_category_id, Spree::PromotionCategory.model_name.human %><br />
        <%= f.collection_select(:promotion_category_id, @promotion_categories, :id, :name, { :include_blank => Spree.t('match_choices.none') }, { :class => 'select2 fullwidth' }) %>
      <% end %>
    </div>
  </div>

  <div id="expiry_fields" class="three columns omega">
    <%= f.field_container :overall_usage_limit do %>
      <%= f.label :usage_limit %><br />
      <%= f.number_field :usage_limit, :min => 0, :class => 'fullwidth' %><br>
      <span class="info">
        <%= Spree.t(:current_promotion_usage, :count => @promotion.usage_count) %>
      </span>
    <% end %>

    <div id="starts_at_field" class="field">
      <%= f.label :starts_at %>
      <%= f.text_field :starts_at, :value => datepicker_field_value(@promotion.starts_at), :class => 'datepicker datepicker-from fullwidth' %>
    </div>

    <div id="expires_at_field" class="field">
      <%= f.label :expires_at %>
      <%= f.text_field :expires_at, :value => datepicker_field_value(@promotion.expires_at), :class => 'datepicker datepicker-to fullwidth' %>
    </div>
  </div>
</div>

lib/sapna_gale_test/backend/app/views/spree/admin/promotions/_promotion_action.html.erb
<div class="promotion_action promotion-block <%= promotion_action.type.to_s.demodulize.underscore %>" id="<%= dom_id promotion_action %>">
  <% type_name = promotion_action.class.name.demodulize.underscore %>
  <h6 class="promotion-title"><%= Spree.t("promotion_action_types.#{type_name}.description") %></h6>
  <% if can?(:destroy, promotion_action) %>
    <%= link_to_with_icon 'trash', '', spree.admin_promotion_promotion_action_path(@promotion, promotion_action), :remote => true, :method => :delete, :class => 'delete' %>
  <% end %>

  <% param_prefix = "promotion[promotion_actions_attributes][#{promotion_action.id}]" %>
  <%= hidden_field_tag "#{param_prefix}[id]", promotion_action.id %>

  <%= render :partial => "spree/shared/error_messages", :locals => { :target => promotion_action } %>
  <%= render :partial => "spree/admin/promotions/actions/#{type_name}",
             :locals => { :promotion_action => promotion_action, :param_prefix => param_prefix } %>
</div>

lib/sapna_gale_test/backend/app/views/spree/admin/promotions/_promotion_rule.html.erb
<div class="promotion_rule promotion-block alpha omega eight columns" id="<%= dom_id promotion_rule %>">
  <% type_name = promotion_rule.class.name.demodulize.underscore %>
  <h6 class='promotion-title <%= 'no-text' if type_name == 'user_logged_in' || type_name == 'first_order'%>'><%= Spree.t("promotion_rule_types.#{type_name}.description") %></h6>
  <% if can?(:destroy, promotion_rule) %>
    <%= link_to_with_icon 'trash', '', spree.admin_promotion_promotion_rule_path(@promotion, promotion_rule), :remote => true, :method => :delete, :class => 'delete' %>
  <% end %>

  <% param_prefix = "promotion[promotion_rules_attributes][#{promotion_rule.id}]" %>
  <%= hidden_field_tag "#{param_prefix}[id]", promotion_rule.id %>
  <%= render :partial => "spree/shared/error_messages", :locals => { :target => promotion_rule } %>
  <%= render :partial => "spree/admin/promotions/rules/#{type_name}", :locals => { :promotion_rule => promotion_rule, :param_prefix => param_prefix } %>
</div>

lib/sapna_gale_test/backend/app/views/spree/admin/promotions/_rules.html.erb
<fieldset id="rule_fields" class ="alpha eight columns no-border-bottom no-border-top">

  <%= form_tag spree.admin_promotion_promotion_rules_path(@promotion), :remote => true, :id => 'new_product_rule_form' do %>
    <fieldset>
      <legend align="center"><%= Spree.t(:rules) %></legend>

      <% if can?(:update, @promotion) %>
        <div class="field">
          <%= label_tag :promotion_rule_type, Spree.t(:add_rule_of_type) %>
          <%= select_tag('promotion_rule[type]', options_for_promotion_rule_types(@promotion), :class => 'select2 fullwidth') %>
        </div>
        <div class="filter-actions actions">
          <%= button Spree.t('actions.add'), 'plus' %>
        </div>
      <% end %>
    </fieldset>
  <% end %>


    <%= form_for @promotion, :url => object_url, :method => :put do |f| %>
      <fieldset class="no-border-top">
        <div id="promotion-pilicy-select" class="align-center row">
          <% Spree::Promotion::MATCH_POLICIES.each do |policy| %>
            <div class="alpha four columns">
              <label><%= f.radio_button :match_policy, policy %> <%= Spree.t "promotion_form.match_policies.#{policy}" %></label>
            </div>
          <% end %>
        </div>

        <div id="rules" class="filter_list row">
          <% if @promotion.rules.any? %>
            <%= render :partial => 'promotion_rule', :collection => @promotion.rules, :locals => {} %>
          <% else %>
            <div class="no-objects-found">
              <%= Spree.t(:no_rules_added) %>
            </div>
          <% end %>
        </div>

        <% if can?(:update, @promotion) %>
          <div class="promotion-update filter-actions actions">
            <%= button Spree.t('actions.update'), 'refresh' %>
          </div>
        <% end %>
      </fieldset>
    <% end %>


</fieldset>

lib/sapna_gale_test/backend/app/views/spree/admin/promotions/_tab.html.erb
<%= tab(:promotions) %>

lib/sapna_gale_test/backend/app/views/spree/admin/promotions/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_promotion) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_promotions_list), admin_promotions_path, :icon => 'arrow-left' %>
    <% if can?(:display, Spree::PromotionCode) %>
      <%= button_link_to Spree.t(:download_promotion_code_list), admin_promotion_promotion_codes_path(promotion_id: @promotion.id, format: :csv), :icon => 'arrow-down' %>
    <% end %>
  </li>
<% end %>

<%= form_for @promotion, :url => object_url, :method => :put do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <% if can?(:update, @promotion) %>
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    <% end %>
  </fieldset>
<% end %>

<div id="promotion-filters" class="row">
  <div id="rules_container" class="alpha eight columns">
    <%= render :partial => 'rules' %>
  </div>

  <div id="actions_container" class="omega eight columns">
    <%= render :partial => 'actions' %>
  </div>
</div>

lib/sapna_gale_test/backend/app/views/spree/admin/promotions/index.html.erb
<% content_for :page_title do %>
  <%= Spree::Promotion.model_name.human(count: :other) %>
<% end %>

<% content_for :page_actions do %>
  <% if can? :create, Spree::Promotion %>
    <li>
      <%= button_link_to Spree.t(:new_promotion), spree.new_admin_promotion_path, :icon => 'plus' %>
    </li>
  <% end %>
<% end %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_promotions_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="four columns alpha">
        <div class="field">
          <%= label_tag :q_name_cont, Spree::Promotion.human_attribute_name(:name) %>
          <%= f.text_field :name_cont, tabindex: 1 %>
        </div>
      </div>

      <div class="four columns">
        <div class="field">
          <%= label_tag :q_codes_value_cont, Spree::Promotion.human_attribute_name(:code) %>
          <%= f.text_field :codes_value_cont, tabindex: 1 %>
        </div>
      </div>

      <div class="four columns">
        <div class="field">
          <%= label_tag :q_path_cont, Spree::Promotion.human_attribute_name(:path) %>
          <%= f.text_field :path_cont, tabindex: 1 %>
        </div>
      </div>

      <div class="four columns omega">
        <div class="field">
          <%= label_tag :q_promotion_category_id_eq, Spree::PromotionCategory.model_name.human %><br>
          <%= f.collection_select(:promotion_category_id_eq, @promotion_categories, :id, :name, { :include_blank => Spree.t('match_choices.all') }, { :class => 'select2 fullwidth' }) %>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div data-hook="admin_promotions_index_search_buttons">
          <%= button Spree.t(:filter_results), 'search' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>


<%= paginate @promotions, theme: "sapna_gale_test_admin" %>

<% if @promotions.any? %>
  <table class="index">
    <colgroup>
      <col style="width: 20%">
      <col style="width: 10%">
      <col style="width: 30%">
      <col style="width: 10%">
      <col style="width: 10%">
      <col style="width: 10%">
      <col style="width: 10%">
    </colgroup>
    <thead>
      <tr>
        <th><%= Spree::Promotion.human_attribute_name(:name) %></th>
        <th><%= Spree::Promotion.human_attribute_name(:code) %></th>
        <th><%= Spree::Promotion.human_attribute_name(:description) %></th>
        <th><%= Spree::Promotion.human_attribute_name(:usage_limit) %></th>
        <th><%= Spree::Promotion.human_attribute_name(:promotion_uses) %></th>
        <th><%= Spree::Promotion.human_attribute_name(:expires_at) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @promotions.each do |promotion| %>
        <tr id="<%= spree_dom_id promotion %>" class="<%= cycle('odd', 'even')%>">
          <td><%= promotion.name %></td>
          <td class="align-center"><%= (promotion.codes.size == 1) ? promotion.codes.first.try!(:value) : Spree.t(:number_of_codes, count: promotion.codes.size) %></td>
          <td><%= promotion.description %></td>
          <td class="align-center"><%= promotion.usage_limit.nil? ? "∞" : promotion.usage_limit  %></td>
          <td class="align-center"><%= Spree.t(:current_promotion_usage, :count => promotion.usage_count) %></td>
          <td class="align-center"><%= promotion.expires_at.to_date.to_s(:short_date) if promotion.expires_at %></td>
          <td class="actions">
            <% if can?(:edit, promotion) %>
              <%= link_to_edit promotion, :no_text => true %>
            <% end %>
            <% if can?(:destroy, promotion) %>
              <%= link_to_delete promotion, :no_text => true %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::Promotion,
                 new_resource_url: new_object_url %>
  </div>
<% end %>

lib/sapna_gale_test/backend/app/views/spree/admin/promotions/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_promotion) %>
<% end %>

<%= form_for :promotion, :url => collection_url do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>